spring:
  application:
    name: admin-server-cloud
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.163.com
    username: wowcheng163@163.com
    password: q125600183!@#
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
  boot:
    admin:
      notify:
        mail:
          to: wowcheng163@163.com
          from: wowcheng163@163.com
server:
  port: 8769

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

