server:
  port: 8085
spring:
  application:
    name: gate-way
  profiles:
    active: service

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug

#---
## DateTime\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: aftert_route
#  cloud:
#    gateway:
#      routes:
#        # \u8DEF\u7531ID
#        - id: after_route
#          # \u8DEF\u7531\u5230uri
#          uri: http://www.baidu.com
#          # \u65AD\u8A00\u6A21\u5F0F
#          predicates:
#            - After=2019-01-20T17:42:47.789+08:00[Asia/Shanghai]
#---
## Header\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: header_route
#  cloud:
#    gateway:
#      routes:
#        # \u8DEF\u7531ID
#        - id: header_route
#          # \u8DEF\u7531\u5230uri
#          uri: http://www.baidu.com
#          # \u65AD\u8A00\u6A21\u5F0F
#          predicates:
#            - Header=X-Request-Id, \d+
#---
## Cookie\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: cookie_route
#  cloud:
#    gateway:
#      routes:
#        # \u8DEF\u7531ID
#        - id: cookie_route
#          # \u8DEF\u7531\u5230uri
#          uri: http://www.baidu.com
#          # \u65AD\u8A00\u6A21\u5F0F
#          predicates:
#            - Cookie=name, asdf
#---
## Host\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: host_route
#  cloud:
#    gateway:
#      routes:
#        # \u8DEF\u7531ID
#        - id: host_route
#          # \u8DEF\u7531\u5230uri
#          uri: http://www.baidu.com
#          # \u65AD\u8A00\u6A21\u5F0F
#          predicates:
#            - Host=**.btbullet.com
#---
## Method\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: method_routew
#  cloud:
#    gateway:
#      routes:
#        # \u8DEF\u7531ID
#        - id: method_routew
#          # \u8DEF\u7531\u5230uri
#          uri: http://www.baidu.com
#          # \u65AD\u8A00\u6A21\u5F0F
#          predicates:
#            - Method=GET
#---
## Path\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: path_route
#  cloud:
#    gateway:
#      routes:
#        - id: path_route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/
#---
## Query\u65AD\u8A00\u5DE5\u5382,\u8BF7\u6C42\u53C2\u6570\u65AD\u8A00\u5DE5\u5382
#spring:
#  profiles: query_route
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://www.baidu.com
#          predicates:
#            - Query=foo, ba
#            - Query=ff, bb
#            - Query=aa