server:
  port: 8769
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chengqiujing/testconfig
          search-paths: respo
          username: chengqiujing
          password: q125600183
      label: master
  application:
    name: config-server-git