server:
  port: 8769

# \u672C\u5730\u914D\u7F6E\u6587\u4EF6\u914D\u7F6E
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server
